### ISSUE TITLE
Update Quora info

### ISSUE THREAD

**Issue by sotojuan** [justdeleteme/justdelete.me#569]
Current Quora info:

> First deactivate your account. Log in, go to 'Settings', 'Privacy', and then 'Deactivate Account'. You can then e-mail privacy@quora.com if you want to completely delete your account.

However, there's a Delete Account button now under Privacy. It deactivates your account for fourteen days before deleting it from public view.

**Comment by skaulana** [comment]
Great catch - I've included this update in my latest PR, linked above.
