### ISSUE TITLE
Update Adobe info

### ISSUE THREAD

**Issue by oscitare** [justdeleteme/justdelete.me#590]
The current info is:

> You have to call them in order to delete your account. Alternatively, you can send them an email.

But now you can just go through [this customer support wizard](https://helpx.adobe.com/contact.html?step=ZNA_id-signing_stillNeedHelp).

**Comment by MarriedPig** [comment]
I also would recommend changing the difficulty to `medium`.

**Comment by MarriedPig** [comment]
In the above commit, I have changed the URL, difficulty, and English and French notes. Other languages need to be modified.

**Comment by tupaschoal** [comment]
Hello @MarriedPig ,

This repo is not being maintained anymore, but we are trying to keep it alive on a fork [here](https://github.com/jdm-contrib), would you kindly submit your issue there and close this one here? :)
