### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rugk** [justdeleteme/justdelete.me#592]
What about adding HTTPS on your site?

With [Let's Encrypt](https://letsencrypt.org/) this is very easy and the service currently is in public beta and you can do it for free.

**Comment by MarriedPig** [comment]
I think this is a great idea! I will definitely remember that one in the future. I'd love to hear what some of this repo's main contributors think of it.

**Comment by anand-bhat** [comment]
:+1:

**Comment by daviddarnes** [comment]
This could also be done with CloudFlare 😄

**Comment by tupaschoal** [comment]
Hello @rugk ,

This repo is not being maintained anymore, but we are trying to keep it alive on a fork [here](https://github.com/jdm-contrib), would you kindly submit your issue there and close this one here? :)

Actually we already have it on an https website there, so you could just close it here ^.^
