### ISSUE TITLE
I need to delete an account from two websites

### ISSUE THREAD

**Issue by JayForShort** [justdeleteme/justdelete.me#655]
1: liveluvcreate.com (seems impossible to delete my account)

 2: dirtsearch.org (seems impossible to delete my account)

**Comment by JayForShort** [comment]
Please help me!!!!

**Comment by neeklamy** [comment]
It looks like you will have to contact both websites: a cursory look doesn’t turn up any way for you to do it yourself.

Often, with older websites the easiest way is to simply remove every detail you can that is on the accounts, then perhaps updating them to email addresses that you don’t actively use – effectively making the accounts ‘useless’.

If you do get a response from either site, it would probably help someone else if you comment here with what they told you.
