### ISSUE TITLE
Etsy doesn't really delete your account

### ISSUE THREAD

**Issue by reclaimer** [justdeleteme/justdelete.me#692]
Yo!

I got my Etsy account deleted, but it doesn't really go away:

> When a member closes an account, it becomes inaccessible and will remain deactivated, unless the member requests it reopened.

> Account information remains securely on file with us, and Etsy has a detailed Privacy Policy that explains how we use members' information. This policy includes a statement regarding data retention:

> “Etsy will retain your information only for as long as is necessary for the purposes set out in this policy, for as long as your account is active, or as needed to provide you services. If you no longer want Etsy to use your information to provide you services, you may close your account. Etsy will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.“

That's from an e-mail with them, which I'm not supposed to reproduce here. Anyway, can I open a PR explaining the data isn't deleted, just deactivated?

**Comment by justdeleteme** [comment]
Hey Reclaimer, go ahead, but perhaps Etsy needs to change their behavior too.

**Comment by reclaimer** [comment]
Hey @justdeleteme,

I've added text for English and Portuguese. What about other languages? Since I've made such huge changes, should I delete the entries in other languages?
