### ISSUE TITLE
last.fm should have "difficulty: impossible"

### ISSUE THREAD

**Issue by sknorr** [justdeleteme/justdelete.me#723]
Quoting from the last.fm account settings page linked to from your site:

> Close account
> 
> This will deactivate your Last.fm user account, so your user page will no longer be shown on the site.

I just checked and you can indeed reactivate the account at a later time, with all user data intact.

**Comment by tupaschoal** [comment]
Hello @sknorr ,

This repo is not being maintained anymore, but we are trying to keep it alive on a fork [here](https://github.com/jdm-contrib), would you kindly submit your issue there and close this one here? :)

**Comment by sknorr** [comment]
-> https://github.com/jdm-contrib/justdelete.me/issues/12
