### ISSUE TITLE
Pastebin outdated: easy to delete

### ISSUE THREAD

**Issue by JonasDralle** [justdeleteme/justdelete.me#729]
Pastebin is not implossible to delete
It's actually very easy.

I contacted support and they gave me this URL:
http://pastebin.com/delete_account

screenshot
![pastebin screenshot](http://i.imgur.com/SohXoQx.png)

**Comment by JonasDralle** [comment]
I'm on it
Will open merge request soon

**Comment by tupaschoal** [comment]
Hello @JonasDralle ,

This repo is not being maintained anymore, but we are trying to keep it alive on a fork [here](https://github.com/jdm-contrib), would you kindly submit your issue there and close this one here? :)

**Comment by JonasDralle** [comment]
okay, thanks for the info

**Comment by JonasDralle** [comment]
[Done](https://github.com/jdm-contrib/justdelete.me/pull/46)
