### ISSUE TITLE
Shipito deletion

### ISSUE THREAD

**Issue by EmmanuelMess** [justdeleteme/justdelete.me#774]
I am lazy, here's the information for shipito:

- `name`: Shipito
- `url`: https://www.shipito.com/es/help/faq/account-navigation
- `difficulty`: `hard`
- `notes`: You have to create a support ticket

**Comment by tupaschoal** [comment]
Hello @EmmanuelMess,

This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)
