### ISSUE TITLE
Discord Account Delete

### ISSUE THREAD

**Issue by OzakIOne** [justdeleteme/justdelete.me#788]
There is a new way to delete a discord account that is easier than the old version
you need to go to user setting>edit account>delete account

**Comment by spencerclrk** [comment]
> There is a new way to delete a discord account that is easier than the old version
> you need to go to user setting>edit account>delete account

https://support.discordapp.com/hc/en-us/articles/212500837-How-do-I-permanently-delete-my-account-?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo2NzgxODMsInVzZXJfaWQiOjM5MTQzMzgyMTQ1MiwidGlja2V0X2lkIjo2MDk2MDA1LCJkZWZsZWN0aW9uX2lkIjozNjAyMzkzODY0MTIsImFydGljbGVzIjpbMjEyNTAwODM3LDM2MDAwNDA2NjM5MSwxMTUwMDMxMTQwOTFdLCJ0b2tlbiI6bnVsbCwiZXhwIjoxNTc5NzA5OTMzfQ.x66OvpdvBlrhSNlWaqmaxOCIBlmmJPgp7AToDib9qVQ&solved=0

**Comment by ghost** [comment]
https://support.discordapp.com/hc/en-us/articles/212500837-How-do-I-permanently-delete-my-account

**Comment by tupaschoal** [comment]
Hello @OzakIOne ,

This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)
