### ISSUE TITLE
Provide a direct URL to the WordPress account deletion page

### ISSUE THREAD

**Issue by winnpixie** [justdeleteme/justdelete.me#808]
WordPress.com appears to have added a function to delete your account since the time of JDM's addition to it, the URL it redirects you to is https://wordpress.com/me/account/close, rather than JDM redirecting you to a Wiki page about account closure

**Comment by tupaschoal** [comment]
Hello @alerithe ,

This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)

**Comment by winnpixie** [comment]
> 
> 
> Hello @alerithe ,
> 
> This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)

Will do
