### ISSUE TITLE
Photobucket

### ISSUE THREAD

**Issue by CarbonaraJack** [justdeleteme/justdelete.me#822]
I believe that the redesign of Photobucket won't allow users to delete their accounts.
The provided link only forwards to a login link that redirects to the homepage of the redesigned website.

**Comment by tupaschoal** [comment]
Hello @CarbonaraJack ,

This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)

**Comment by CarbonaraJack** [comment]
> Hello @CarbonaraJack ,
> 
> This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)

Sure thing. Thanks for the pointer
