### ISSUE TITLE
Is it possible to delete a Godaddy account

### ISSUE THREAD

**Issue by szepeviktor** [justdeleteme/justdelete.me#825]
Currently we have

>  		"difficulty" : "impossible",

I've just deleted my account at a reseller of Godaddy

![kép](https://user-images.githubusercontent.com/952007/75160774-ee7a9a80-571a-11ea-8f8d-7f052a484006.png)

The link is: https://account.secureserver.net/preferences

**Comment by tupaschoal** [comment]
So does this delete your `Godaddy` account too? That's not clear to me.

**Comment by tupaschoal** [comment]
Hello @szepeviktor ,

This repo is not being maintained anymore, but we've kept it alive and updated [on a detached fork](https://github.com/jdm-contrib/jdm). If still applicable, would you kindly submit your issue there and close this one here? :)

**Comment by szepeviktor** [comment]
Thank you!
So https://backgroundchecks.org/justdeleteme/ contains **outdated** information?

**Comment by tupaschoal** [comment]
Yes, this repo hasn't been updated in almost 3y
