### ISSUE TITLE
500px deletion process is actually `hard`

### ISSUE THREAD

**Issue by giovariot** [justdeleteme/justdelete.me#828]
The current 500px record links to account "deactivation", which doesn't delete the account completely.

In order to delete the account completely you have to follow this guide on their site, submit a request to their customer help asking for the deletion.
https://support.500px.com/hc/en-us/articles/360009701153-How-do-I-delete-my-account-

The link should then be updated and the difficulty set to `hard`

**Comment by tupaschoal** [comment]
@giovariot the repository lives on https://github.com/jdm-contrib/jdm if you think this issue is still applicable, speak up there :)
