### ISSUE TITLE
add ctrader

### ISSUE THREAD

**Issue by sinasalimipour** [justdeleteme/justdelete.me#866]
https://ctrader.com
ctrader is a forex trader 
there is https://help.ctrader.com/ctrader-id/delete
but it says just email us

**Comment by tupaschoal** [comment]
Hello @sinagun ,

This repo has been dormant for years, I suggest you submit your PR/issue on our maintained fork over at https://github.com/jdm-contrib/jdm

**Comment by sinasalimipour** [comment]
Hello@[tupaschoal](https://github.com/tupaschoal)

oke thank you😊
